### PR TITLE
Update sink example README.md

### PR DESCRIPTION
**Pull request by maximilien**
add `-n redex` to correctly find the `redistreamsinkmystream` service

## Proposed Changes

- add `-n redex`

### CODE REVIEW

**Comment by aavarghese** [comment]
@maximilien `-n redex` already exists in that line https://github.com/knative-sandbox/eventing-redis/pull/96/files#diff-877851ba8b019e4c4569bc635f56ef8e1129414baa9c9ec9ba9d11062b199f04L88, before modification.

**Comment by maximilien** [comment]
> @maximilien `-n redex` already exists in that line https://github.com/knative-sandbox/eventing-redis/pull/96/files#diff-877851ba8b019e4c4569bc635f56ef8e1129414baa9c9ec9ba9d11062b199f04L88, before modification.

this is not to create but to resolve the `kubectl` call

**Comment by aavarghese** [comment]
@maximilien yeah, the `-n` was added recently as part of my sink updates PR #86, specifically [here](https://github.com/knative-sandbox/eventing-redis/pull/86/files#diff-877851ba8b019e4c4569bc635f56ef8e1129414baa9c9ec9ba9d11062b199f04R85). I'm thinking you had the older version of README for sink. Let me know if the latest steps work for you.

**Comment by maximilien** [comment]
OK closing. You are correct was fix in your PR. Though these kind of flags are better listed at start of command... but maybe that’s just me. Cheers.

**Pull request closed without merging**
